version: '3.8'

services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - company-info-service
      - news-service
      - currency-service
      - historical-analytics-service
      - stocks-service

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"

  company-info-service:
      build: ./company-info-service
      ports:
        - "8081:8080"

  news-service:
      build: ./news-service
      ports:
        - "8082:8080"

  currency-service:
      build: ./currency-service
      ports:
        - "8083:8080"

  historical-analytics-service:
      build: ./historical-analytics-service
      ports:
        - "8084:8080"

  stocks-service:
    build: ./stocks-service
    ports:
      - "8085:8080"
    environment:
      - POLYGON_API_KEY=V4_aPjfLf3uRm1v8EO3SRFvJfOM4WtDp

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge