version: '3.8'

services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - company-info-service
      - news-service
      - currency-service
      - historical-analytics-service

  company-info-service:
      build: ./company-info-service
      ports:
        - "8081:8081"

  news-service:
      build: ./news-service
      ports:
        - "8082:8082"

  currency-service:
      build: ./currency-service
      ports:
        - "8083:8083"

  historical-analytics-service:
      build: ./historical-analytics-service
      ports:
        - "8084:8084"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
