version: '3.8'

services:

  company-info-service:
    build:
      context: ./company-info-service
    ports:
      - "8081:8080"
    container_name: company-info-service

  currency-service:
      build:
        context: ./currency-service
      ports:
        - "8082:8080"
      container_name: currency-service

  news-service:
      build:
        context: ./news-service
      ports:
        - "8083:8080"
      container_name: news-service

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
