version: '3.8'

services:

  company-db:
    image: postgres:16
    container_name: company-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: company_info_db
    ports:
      - "5432:5432"
    networks:
      - stocknet

  news-db:
    image: postgres:16
    container_name: news-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_db
    ports:
      - "5433:5432"
    networks:
      - stocknet

  historical-db:
    image: postgres:16
    container_name: historical-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: historical_db
    ports:
      - "5434:5432"
    networks:
      - stocknet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - stocknet

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - company-info-service
      - news-service
      - currency-service
      - historical-analytics-service
      - stocks-service
    networks:
      - stocknet

  company-redis:
    image: redis:7-alpine
    container_name: company-redis
    ports:
      - "6380:6379"
    networks:
      - stocknet

  currency-redis:
    image: redis:7-alpine
    container_name: currency-redis
    ports:
      - "6381:6379"
    networks:
      - stocknet

  company-info-service:
      build: ./company-info-service
      container_name: company-info-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://company-db:5432/company_info_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        POLYGON_API_KEY: V4_aPjfLf3uRm1v8EO3SRFvJfOM4WtDp
        SPRING_REDIS_HOST: company-redis
        SPRING_REDIS_PORT: 6379
      depends_on:
          - company-db
          - company-redis
      ports:
        - "8081:8080"
      networks:
        - stocknet

  news-service:
      build: ./news-service
      container_name: news-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://news-db:5432/news_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        POLYGON_API_KEY: V4_aPjfLf3uRm1v8EO3SRFvJfOM4WtDp
      depends_on:
        - news-db
      ports:
        - "8082:8080"
      networks:
        - stocknet

  currency-service:
    build: ./currency-service
    container_name: currency-service
    ports:
      - "8083:8080"
    environment:
      SPRING_REDIS_HOST: currency-redis
    depends_on:
      - currency-redis
    networks:
      - stocknet

  historical-analytics-service:
      build: ./historical-analytics-service
      container_name: historical-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://historical-db:5432/historical_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        POLYGON_API_KEY: V4_aPjfLf3uRm1v8EO3SRFvJfOM4WtDp
      depends_on:
        - historical-db
      ports:
        - "8084:8080"
      networks:
        - stocknet

  stocks-service:
      build: ./stocks-service
      container_name: stocks-service
      ports:
        - "8085:8080"
      environment:
        POLYGON_API_KEY: V4_aPjfLf3uRm1v8EO3SRFvJfOM4WtDp
      networks:
        - stocknet

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - monitoring

networks:
  stocknet:

  monitoring:
    driver: bridge