version: '3.8'

services:

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: company_info_db
    ports:
      - "5432:5432"
    networks:
      - stocknet

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - stocknet

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - company-info-service
      - news-service
      - currency-service
      - historical-analytics-service
      - stocks-service
    networks:
      - stocknet

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - stocknet

  company-info-service:
      build: ./company-info-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/company_info_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        POLYGON_API_KEY: V4_aPjfLf3uRm1v8EO3SRFvJfOM4WtDp
        SPRING_REDIS_HOST: redis
        SPRING_REDIS_PORT: 6379
      depends_on:
          - postgres
      ports:
        - "8081:8080"
      networks:
        - stocknet

  news-service:
      build: ./news-service
      ports:
        - "8082:8080"
      networks:
        - stocknet

  currency-service:
      build: ./currency-service
      ports:
        - "8083:8080"

  historical-analytics-service:
      build: ./historical-analytics-service
      ports:
        - "8084:8080"

  stocks-service:
      build: ./stocks-service
      ports:
        - "8085:8080"
      environment:
        - POLYGON_API_KEY=${POLYGON_API_KEY}

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - monitoring

networks:
  stocknet:

  monitoring:
    driver: bridge