server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: ticker-service
          uri: http://company-info-service:8080
          predicates:
            - Path=/api/tickers/**

        - id: company-service
          uri: http://company-info-service:8080
          predicates:
            - Path=/api/companies/**

        - id: news-service
          uri: http://news-service:8080
          predicates:
            - Path=/api/news/**

        - id: currency-service
          uri: http://currency-service:8080
          predicates:
            - Path=/api/currency/**

        - id: historical-analytics-service
          uri: http://historical-analytics-service:8080
          predicates:
            - Path=/api/historical/**

        - id: stocks-service
          uri: http://stocks-service:8080
          predicates:
            - Path=/api/stocks/**

        - id: stocks-service-ws
          uri: ws://stocks-service:8080
          predicates:
          - Path=/ws/stocks/**

        - id: notification-service
          uri: http://notification-service:8080
          predicates:
              - Path=/api/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true