server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ticker-service
          uri: http://company-info-service:8080
          predicates:
            - Path=/api/tickers/**

        - id: company-service
          uri: http://company-info-service:8080
          predicates:
            - Path=/api/companies/**

        - id: news-service
          uri: http://news-service:8080
          predicates:
            - Path=/api/news/**

        - id: currency-service
          uri: http://currency-service:8080
          predicates:
            - Path=/api/currency/**

        - id: historical-analytics-service
          uri: http://historical-analytics-service:8080
          predicates:
            - Path=/api/historical/**

        - id: stocks-service
          uri: http://stocks-service:8080
          predicates:
            - Path=/api/stocks/**

        - id: stocks-service-ws
          uri: ws://stocks-service:8080
          predicates:
          - Path=/ws/stocks/**

        - id: notification-service
          uri: http://notification-service:8080
          predicates:
              - Path=/api/notifications/**

        - id: company-info-docs
          uri: http://company-info-service:8080
          predicates:
            - Path=/openapi/company-info
          filters:
            - RewritePath=/openapi/stocks-service, /api-docs

        - id: news-service-docs
          uri: http://news-service:8080
          predicates:
            - Path=/openapi/news-service
          filters:
            - RewritePath=/openapi/stocks-service, /api-docs

        - id: currency-service-docs
          uri: http://currency-service:8080
          predicates:
            - Path=/openapi/currency-service
          filters:
            - RewritePath=/openapi/stocks-service, /api-docs

        - id: stocks-service-docs
          uri: http://stocks-service:8080
          predicates:
            - Path=/openapi/stocks-service
          filters:
            - RewritePath=/openapi/stocks-service, /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        "[http.server.requests]": 25ms,50ms,100ms,200ms,400ms,800ms
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /swagger
    urls:
      - url: /openapi/company-info
        name: company-info
      - url: /openapi/news-service
        name: news-service
      - url: /openapi/currency-service
        name: currency-service
      - url: /openapi/stocks-service
        name: stocks-service