server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: company-service
          uri: http://company-info-service:8081
          predicates:
            - Path=/api/companies/**

        - id: news-service
          uri: http://news-service:8082
          predicates:
            - Path=/api/news/**

        - id: currency-service
          uri: http://currency-service:8083
          predicates:
            - Path=/api/currency/**

        - id: historical-analytics-service
          uri: http://historical-analytics-service:8084
          predicates:
            - Path=/api/historical/**