server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: company-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/companies/**

        - id: news-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/news/**