polygon:
  api:
    key: ${POLYGON_API_KEY:dummy_key_for_tests}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        "[http.server.requests]": 25ms,50ms,100ms,200ms,400ms,800ms
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

server:
  tomcat:
    mbeanregistry:
      enabled: true
    max-connections: 10000
    threads:
      max: 400
    accept-count: 1000
  port: 8080
  address: 0.0.0.0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operationsSorter: method
    tagsSorter: alpha
spring:
  application:
    name: stocks-service