spring:
  data:
    redis:
      host: redis
      port: 6379
    cache:
      type: redis

server:
  port: 8080
  address: 0.0.0.0

polygon:
  api:
    key: V4_aPjfLf3uRm1v8EO3SRFvJfOM4WtDp

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true