external:
  polygon:
    base-url: https://api.polygon.io

spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: company-info-service
#  datasource:
#    url: jdbc:postgresql://company-db:5432/company_info_db
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: company-redis
      port: 6379

server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8080
  address: 0.0.0.0

polygon:
  api:
    key: ${POLYGON_API_KEY}


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        "[http.server.requests]": 25ms,50ms,100ms,200ms,400ms,800ms
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      polygonCompanyCB:
        sliding-window-type: TIME_BASED
        sliding-window-size: 60
        minimum-number-of-calls: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 70
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        recordExceptions:
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException
          - java.util.concurrent.TimeoutException
  retry:
    instances:
      readSafe:
        max-attempts: 2
        wait-duration: 150ms
        enable-exponential-backoff: true
        retry-exceptions:
          - java.net.SocketTimeoutException
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
          - java.util.concurrent.TimeoutException

  bulkhead:
    instances:
      companyRead:
        max-concurrent-calls: 50
        max-wait-duration:
          seconds: 0
      companyWrite:
        max-concurrent-calls: 30
        max-wait-duration:
          seconds: 0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operationsSorter: method
    tagsSorter: alpha