polygon:
  api:
    key: ${POLYGON_API_KEY}

server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: historical-service
  #  datasource:
#    url: jdbc:postgresql://historical-db:5432/historical_db
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        "[http.server.requests]": 25ms,50ms,100ms,200ms,400ms,800ms
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      polygonHistCB:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 50
        slowCallDurationThreshold: 5s
        slowCallRateThreshold: 70
        waitDurationInOpenState: 45s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      polygonHistRetry:
        maxAttempts: 2
        waitDuration: 300ms
        retryExceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
        ignoreExceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - org.springframework.web.client.HttpClientErrorException

  ratelimiter:
    instances:
      polygonHistRL:
        limitForPeriod: 4
        limitRefreshPeriod: 1s
        timeoutDuration: 0

  bulkhead:
    instances:
      polygonHistBH:
        maxConcurrentCalls: 12
        maxWaitDuration: 0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operationsSorter: method
    tagsSorter: alpha